/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include "DuktapeEngine.h"



#define convert_to_context(ptr)    ((duk_context *)((intptr_t)ptr))

#define convert_to_ptr(ctx)    ((jlong)((intptr_t)ctx))

#define convert_ptr_to_long(ctx)    ((jlong)((intptr_t)ctx))

#define convert_long_to_ptr(ctx)   ((void *)((intptr_t)ptr))

#define  JAVA_OBJECT_MARK    "__j"

#define  JS_REF_MARK    "__r"

#define  JAVA_METHOD_MARK    "__c"

#define  JAVA_GET_MARK    "__g"

#define  JAVA_SET_MARK    "__s"


#define  JAVA_ENGINE_MARK    "__engine"

static jclass java_api_class = NULL;

static jmethodID java_function_method = NULL;

static jmethodID java_field_get_method = NULL;

static jmethodID java_import_class_method = NULL;

static jmethodID java_field_set_method = NULL;

static jmethodID java_new_instance_method = NULL;

static jmethodID java_exception_get_stack_trace_method = NULL;

static jclass js_ref_class = NULL;
static jmethodID js_ref_new_method = NULL;
static jmethodID js_ref_get_ref_method = NULL;

static jclass java_boolean_class  = NULL;
static jclass java_integer_class  = NULL;
static jclass java_long_class  = NULL;
static jclass java_double_class  = NULL;
static jclass java_float_class  = NULL;
static jclass java_short_class  = NULL;
static jclass java_byte_class  = NULL;
static jclass java_number_class  = NULL;
static jmethodID java_number_get_double_value_method  = NULL;
static jmethodID java_boolean_get_boolean_value_method  = NULL;

static JavaVM*  jvm;


void duk_push_java_object(duk_context *ctx, JNIEnv *env, jobject object);

int duk_push_java_object_array(duk_context *ctx, JNIEnv *env, jobjectArray args);

int  duk_new_java_class(duk_context *ctx);

void duk_mark_jsobject_to_java_object(duk_context *ctx, int index, JNIEnv *env, jobject object);

jobjectArray duk_to_java_object_array(duk_context *ctx, int start, int num, JNIEnv*  env);

const char * duk_js_error_to_string(duk_context *ctx, int index);

JNIEnv*  get_java_jni_env();



jobject get_engine_from_context(duk_context *ctx){
	    duk_push_global_object(ctx);
		if(duk_get_prop_string(ctx, -1, JAVA_ENGINE_MARK)){
			jobject  engine =  duk_to_pointer(ctx, -1);
		    duk_pop_2(ctx);
		    return engine;
		}
		duk_pop_2(ctx);
		return NULL;
}

const char * duk_js_error_to_string(duk_context *ctx, int index){
	DEBUG_LOG("ScriptEngine","duk_js_error_to_string %d  %d", index, duk_is_error(ctx, index));
	if(duk_get_prop_string(ctx, index, "lineNumber")){
         int lineNumber = duk_get_int(ctx, -1);
         duk_pop(ctx);
         duk_push_sprintf(ctx, " %s  at javascript source %d line", duk_to_string(ctx, index), lineNumber);
         if(index < 0){
            duk_replace(ctx, index - 1);
         }else{
        	    duk_replace(ctx, index);
         }
         return duk_to_string(ctx,index);
	}
	duk_pop(ctx);
	return duk_to_string(ctx, index);
}


/**
 *
 * performance tips
 * https://www.ibm.com/developerworks/library/j-jni/
 * */
jobject duk_to_java_object(duk_context *ctx, JNIEnv*  env, int i){
	int type = duk_get_type(ctx, i);
	if(type == DUK_TYPE_BOOLEAN){
		jboolean value = duk_to_boolean(ctx, i);
		DEBUG_LOG("ScriptEngine","invoke_java_method call, convert %d args to boolean %d", i, value);
		jmethodID methodID = (*env)->GetMethodID(env, java_boolean_class, "<init>", "(Z)V");
		jobject booleanObject = (*env)->NewObject(env, java_boolean_class, methodID, value);
		return  booleanObject;
	}else if(type == DUK_TYPE_NUMBER){
		jdouble value = duk_to_number(ctx, i);
		jclass doubleClass = (*env)->FindClass(env, "java/lang/Double");
		jmethodID methodID = (*env)->GetMethodID(env, doubleClass, "<init>", "(D)V");
		jobject numberObject = (*env)->NewObject(env, doubleClass, methodID, value);
		(*env)->DeleteLocalRef(env, doubleClass);
		DEBUG_LOG("ScriptEngine","invoke_java_method call, convert %d args to number %f", i, value);
		return numberObject;
	 }else if(type == DUK_TYPE_STRING){
		    const char*  chs = duk_to_string(ctx, i);
		    DEBUG_LOG("ScriptEngine","invoke_java_method call, convert %d args to string %s", i, chs);
		   return (*env)->NewStringUTF(env, chs);
	  }else if(type == DUK_TYPE_OBJECT){
		  if(duk_get_prop_string(ctx, i, JAVA_OBJECT_MARK)){
			    DEBUG_LOG("ScriptEngine","invoke_java_method call, convert %d args to java object", i);
		  		jobject  value = duk_to_pointer(ctx, -1);
		  	    duk_pop(ctx);
		  	    return (*env)->NewLocalRef(env, value);
		  }else{
			  duk_pop(ctx);
			  if(duk_get_prop_string(ctx, i, JS_REF_MARK)){
				  DEBUG_LOG("ScriptEngine","reuse javascript object's JSRef");
				  jweak  weakRef = duk_to_pointer(ctx, -1);
				  jobject jsRefObject = (*env)->NewLocalRef(env, weakRef);
				  duk_pop(ctx);
				  if(jsRefObject != NULL){
					  return jsRefObject;
				  }
			  }else{
				  duk_pop(ctx);
			  }
			  duk_dup(ctx, i);
			  jint ref = duk_js_ref(ctx);
			  if(ref != 0){
				  DEBUG_LOG("ScriptEngine","convert javascript object to JSRef Ref Value %d ", ref);
				  jobject engine = get_engine_from_context(ctx);
				  DEBUG_LOG("ScriptEngine","convert javascript object to JSRef Ref Value");
				  jobject jsRefObject = (*env)->NewObject(env, js_ref_class, js_ref_new_method, engine, ref);
				  jweak jsWeakRef = (*env)->NewWeakGlobalRef(env, jsRefObject);
				  duk_dup(ctx, i);
				  duk_push_pointer(ctx, jsWeakRef);
				  duk_put_prop_string(ctx, -2, JS_REF_MARK);
				  duk_pop(ctx);
				  DEBUG_LOG("ScriptEngine","convert javascript object to JSRef Ref Value Success");
				  return jsRefObject;
			  }
			  return NULL;
		  }
	  }
	  DEBUG_LOG("ScriptEngine","invoke_java_method call, unhandled type convert %d args to null %s", i, duk_to_string(ctx, i));
	  return NULL;
}



int invoke_java_method_call(duk_context *ctx) {
    int num = duk_get_top(ctx);
	const char * method = duk_to_string(ctx, 0);
	DEBUG_LOG("ScriptEngine","invoke_java_method call, method name %s  args num %d",  method, (num - 1));
	duk_push_this(ctx);
	if(duk_get_prop_string(ctx, -1, JAVA_OBJECT_MARK)){
		jobject  ref = duk_to_pointer(ctx, -1);
		JNIEnv*  env =  get_java_jni_env();
		DEBUG_LOG("ScriptEngine","invoke_java_method call, method  new String  %s", method);
		jstring methodName = (*env)->NewStringUTF(env, method);
	    jobjectArray args = duk_to_java_object_array(ctx, 1, num-1, env);
	    DEBUG_LOG("ScriptEngine","invoke_java_method call, with args %p   %p", java_api_class,  java_function_method);
		jobject value =  (*env)->CallStaticObjectMethod(env, java_api_class, java_function_method, ref, methodName, args);
		jthrowable exp = ( *env)->ExceptionOccurred(env);
        if(exp != NULL){
        	      ( *env)->ExceptionClear(env);
        	      jstring exceptionMessage = (*env)->CallStaticObjectMethod(env, java_api_class, java_exception_get_stack_trace_method, exp);
              jboolean isCopy = JNI_FALSE;
        	      const char* cstrMessage = (*env)->GetStringUTFChars(env, exceptionMessage, &isCopy);
        	      duk_push_error_object(ctx, DUK_ERR_EVAL_ERROR, "invoke java method  %s exception \n %s",  method, cstrMessage);
        	      (*env)->ReleaseStringUTFChars(env, exceptionMessage, cstrMessage);
        	      ( *env)->DeleteLocalRef(env , exceptionMessage);
        	      (*env)->DeleteLocalRef(env, args);
        	      (*env)->DeleteLocalRef(env, methodName);
        	      duk_throw(ctx);
        	      return 0;
        }
		duk_push_java_object(ctx, env, value);
	    (*env)->DeleteLocalRef(env, value);
	    (*env)->DeleteLocalRef(env, args);
	    (*env)->DeleteLocalRef(env, methodName);
	    DEBUG_LOG("ScriptEngine","invoke_java_method call with args success ");
		return 1;
	}else{
		duk_pop(ctx);
		duk_insert(ctx, 0);
		DEBUG_LOG("ScriptEngine","invoke_script_prop call, with args  num %d ", duk_get_top(ctx));
		if(duk_pcall_prop(ctx, 0, num - 1) != DUK_EXEC_SUCCESS){
			LOGE("ScriptEngine","ScriptEngine call %s method %s error %s", duk_to_string(ctx, 0), method, duk_js_error_to_string(ctx, -1));
			duk_pop(ctx);
			duk_push_null(ctx);
		}
		DEBUG_LOG("ScriptEngine","invoke_script_prop call, duk_get_prop_string with args  num %d ", duk_get_top(ctx));
		return 1;
	}
}




static int java_object_finalizer(duk_context *ctx) {
	int n = duk_get_top(ctx);
	DEBUG_LOG("ScriptEngine",  "java_object_finalizer enter %d", n);
	if(duk_get_prop_string(ctx, -1, JAVA_OBJECT_MARK)){
		jobject  ref = duk_to_pointer(ctx, -1);
		if(ref != NULL){
			DEBUG_LOG("ScriptEngine",  "java_object_finalizer find free new_java_object");
			JNIEnv *env = get_java_jni_env();
			(*env)->DeleteGlobalRef(env, ref);
		}
	}else{
		DEBUG_LOG("ScriptEngine",  "java_object_finalizer error, none find free new_java_object");
	}
	return 0;
}


static int java_object_to_string(duk_context *ctx) {
	int n = duk_get_top(ctx);
	DEBUG_LOG("ScriptEngine",  "java_object_to_string enter %d", n);
	duk_push_this(ctx);
	if(duk_get_prop_string(ctx, -1, JAVA_OBJECT_MARK)){
		DEBUG_LOG("ScriptEngine",  "java_object_to_string enter java object ");
		jobject  ref = duk_to_pointer(ctx, -1);
		if(ref == NULL){
			 duk_push_null(ctx);
			 return 1;
		}
		JNIEnv*  env =  get_java_jni_env();
		DEBUG_LOG("ScriptEngine",  "java_object_to_string enter java end");
		jclass   refClass = (*env)->GetObjectClass(env, ref);
		jmethodID method = (*env)->GetMethodID(env, refClass, "toString", "()Ljava/lang/String;");
		jstring  value =  (*env)->CallObjectMethod(env, ref, method);
		jboolean iscopy = JNI_FALSE;
		const char* src =  ((*env)->GetStringUTFChars(env, value, &iscopy));
		DEBUG_LOG("ScriptEngine",  "java_object_to_string src %s", src );
        duk_push_string(ctx, src);
        (*env)->ReleaseStringUTFChars(env, value, src);
		(*env)->DeleteLocalRef(env, value);
		(*env)->DeleteLocalRef(env, refClass);
		DEBUG_LOG("ScriptEngine",  "java_object_to_string success");
		return 1;
	}else{
		DEBUG_LOG("ScriptEngine",  "java_object_to_string error");
	}
	return 0;
}

static duk_ret_t duk_java_property_get(duk_context *ctx) {
	const char* key  = duk_to_string(ctx, 0);
	DEBUG_LOG("ScriptEngine", "duk_java_property_get  key %s", key);
	duk_push_this(ctx);
	if(duk_get_prop_string(ctx, -1, JAVA_OBJECT_MARK)){
		jobject  ref = duk_to_pointer(ctx, -1);
		JNIEnv*  env =  get_java_jni_env();
		jstring fieldName = (*env)->NewStringUTF(env, key);
		DEBUG_LOG("ScriptEngine", "duk_get_prop_string  key %s", key);
		jobject  value =  (*env)->CallStaticObjectMethod(env, java_api_class, java_field_get_method, ref, fieldName);
		jthrowable exp = ( *env)->ExceptionOccurred(env);
		if(exp != NULL){
				  ( *env)->ExceptionClear(env);
				  jstring exceptionMessage = (*env)->CallStaticObjectMethod(env, java_api_class, java_exception_get_stack_trace_method, exp);
			      jboolean isCopy = JNI_FALSE;
				  const char* cstrMessage = (*env)->GetStringUTFChars(env, exceptionMessage, &isCopy);
				  duk_push_error_object(ctx, DUK_ERR_EVAL_ERROR, "get java property %s error \n %s",  key, cstrMessage);
				  (*env)->ReleaseStringUTFChars(env, exceptionMessage, cstrMessage);
				  ( *env)->DeleteLocalRef(env , exceptionMessage);
				  (*env)->DeleteLocalRef(env, value);
				  (*env)->DeleteLocalRef(env, fieldName);
				  duk_throw(ctx);
				  return 0;
		 }
		DEBUG_LOG("ScriptEngine", "duk_get_prop_string push object %s value ", key);
		duk_push_java_object(ctx, env, value);
		DEBUG_LOG("ScriptEngine", "duk_get_prop_string  push object %s success", key);
		(*env)->DeleteLocalRef(env, value);
		(*env)->DeleteLocalRef(env, fieldName);
		return 1;
	}else{
		duk_get_prop_string(ctx, 1, key);
		if(duk_is_undefined(ctx, -1)){
			LOGW("ScriptEngine", "ScriptEngine warn property  %s not found ", key);
		}
		return 1;
	}
}

static duk_ret_t duk_java_property_set(duk_context *ctx) {
	 const char* key  = duk_to_string(ctx, 0);
	 DEBUG_LOG("ScriptEngine", "duk_java_property_set  key %s ", key);
	 duk_push_this(ctx);
     if(duk_get_prop_string(ctx, -1, JAVA_OBJECT_MARK)){
			jobject  ref = duk_to_pointer(ctx, -1);
			JNIEnv*  env =  get_java_jni_env();
			jstring fieldName = (*env)->NewStringUTF(env, key);
			jobject  fieldValue = duk_to_java_object(ctx, env, 1);
			DEBUG_LOG("ScriptEngine", "duk_java_property_set  call staticVoidMethod %s ", key);
			(*env)->CallStaticVoidMethod(env, java_api_class, java_field_set_method, ref, fieldName, fieldValue);
			DEBUG_LOG("ScriptEngine", "duk_java_property_set  call staticVoidMethod Success");
			jthrowable exp = ( *env)->ExceptionOccurred(env);
			if(exp != NULL){
					  (*env)->ExceptionClear(env);
					  jstring exceptionMessage = (*env)->CallStaticObjectMethod(env, java_api_class, java_exception_get_stack_trace_method, exp);
				      jboolean isCopy = JNI_FALSE;
					  const char* cstrMessage = (*env)->GetStringUTFChars(env, exceptionMessage, &isCopy);
					  duk_push_error_object(ctx, DUK_ERR_EVAL_ERROR, "get java property %s error \n %s",  key, cstrMessage);
					  (*env)->ReleaseStringUTFChars(env, exceptionMessage, cstrMessage);
					  ( *env)->DeleteLocalRef(env , exceptionMessage);
					  (*env)->DeleteLocalRef(env, fieldValue);
					  (*env)->DeleteLocalRef(env, fieldName);
					  duk_throw(ctx);
					  return 0;
			 }
			(*env)->DeleteLocalRef(env, fieldValue);
			(*env)->DeleteLocalRef(env, fieldName);
			return 0;
	 }else{
		  DEBUG_LOG("ScriptEngine", "duk_java_property_set  key %d ", duk_get_top(ctx));
		  duk_pop(ctx);
		  DEBUG_LOG("ScriptEngine", "duk_java_property_set  key %d ", duk_get_top(ctx));
		  duk_replace(ctx, 0);
		  DEBUG_LOG("ScriptEngine", "duk_java_property_set  key %d ", duk_get_top(ctx));
	      duk_put_prop_string(ctx, 0, key);
	      DEBUG_LOG("ScriptEngine", "duk_java_property_set  key %d ", duk_get_top(ctx));
		  return 0;
	 }
}


void duk_push_java_object(duk_context *ctx, JNIEnv *env, jobject object){
	if(object == NULL){
		duk_push_null(ctx);
		return;
	}
	if((*env)->IsInstanceOf(env, object, js_ref_class)){
		jint  ref = (*env)->CallIntMethod(env, object, js_ref_get_ref_method);
		duk_push_js_ref(ctx, ref);
		return;
	}
	if((*env)->IsInstanceOf(env, object, java_number_class)){
		jdouble num = (*env)->CallDoubleMethod(env, object, java_number_get_double_value_method);
		duk_push_global_object(ctx);
		duk_get_prop_string(ctx, -1, "Number");
		duk_push_number(ctx, num);
		duk_new(ctx, 1);
		duk_mark_jsobject_to_java_object(ctx, -1, env, object);
		duk_remove(ctx, -2);
        return;
	}
	if((*env)->IsInstanceOf(env, object, java_boolean_class)){
		jboolean value = (*env)->CallBooleanMethod(env, object, java_boolean_get_boolean_value_method);
		if(value){
			duk_push_true(ctx);
		}else{
			duk_push_false(ctx);
		}
		return;
	}
	duk_push_object(ctx);  //empty target
	duk_mark_jsobject_to_java_object(ctx, -1, env, object);
}

int duk_push_java_object_array(duk_context *ctx, JNIEnv *env, jobjectArray args){
	  jsize length =  0;
	  if(args != NULL){
		 length = (*env)->GetArrayLength(env, args);
	  }
	  DEBUG_LOG("ScriptEngine","duk_push_java_object_array length %d", length);
	  for(int i=0; i<length; i++){
		  jobject object =  (*env)->GetObjectArrayElement(env, args, i);
		  duk_push_java_object(ctx, env, object);
	  }
	  return length;
}



void duk_mark_jsobject_to_java_object(duk_context *ctx, int index, JNIEnv *env, jobject object){
	jobject  ref = ((*env)->NewGlobalRef(env, object));
	duk_push_pointer(ctx, ref);
	DEBUG_LOG("ScriptEngine", "duk_push_pointer success %d", index);
    duk_put_prop_string(ctx, index - 1, JAVA_OBJECT_MARK);
	duk_push_c_function(ctx, java_object_to_string, 0);
	duk_put_prop_string(ctx, index - 1, "toString");
	duk_push_c_function(ctx, java_object_finalizer, 1);
	duk_set_finalizer(ctx, index - 1);
	DEBUG_LOG("ScriptEngine",  "new_java_object success");
}





int duk_import_java_class(duk_context *ctx){
	DEBUG_LOG("DuktapeEngine", "className duk_import_java_class");
	int n = duk_get_top(ctx);
	const char* className = duk_to_string(ctx, 0);
	const char*  shortName = NULL;
	if(n > 1){
		shortName = duk_to_string(ctx, 1);
	}else{
		shortName = strrchr(className, '.');
		shortName++;
	}
	DEBUG_LOG("DuktapeEngine", "className %s  shorName %s",className, shortName);

	duk_push_global_object(ctx);
	duk_push_c_function(ctx, duk_new_java_class,  DUK_VARARGS);

	JNIEnv *env = get_java_jni_env();
	jstring  fullClassName = (*env)->NewStringUTF(env, className);
    jobject  value =  (*env)->CallStaticObjectMethod(env, java_api_class, java_import_class_method, fullClassName);
	duk_mark_jsobject_to_java_object(ctx, -1, env, value);
    (*env)->DeleteLocalRef(env, value);
	(*env)->DeleteLocalRef(env, fullClassName);
	duk_push_object(ctx);
    duk_push_string(ctx, className);
    duk_put_prop_string(ctx, -2, "className");
    duk_put_prop_string(ctx, -2, "prototype");
    duk_put_prop_string(ctx, -2, shortName);
    duk_pop(ctx);
    return 0;
}

jobjectArray duk_to_java_object_array(duk_context *ctx, int start, int num, JNIEnv*  env){
	 jclass objectClass = (*env)->FindClass(env, "java/lang/Object");
	 jobjectArray args = (*env)->NewObjectArray(env, num, objectClass, NULL);
	 for(int i=0; i< num; i++){
	    	  jobject   value = duk_to_java_object(ctx, env, i + start);
	    	  DEBUG_LOG("ScriptEngine","duk_new_java_class duk_to_java_object %d   success %d", i, value == NULL);
	    	  (*env)->SetObjectArrayElement(env, args,  i, value);
	    	  (*env)->DeleteLocalRef(env, value);
	    	  DEBUG_LOG("ScriptEngine","duk_new_java_class  duk_to_java_object %d   success", i);
	 }
	 (*env)->DeleteLocalRef(env, objectClass);
	 return args;
}



int duk_new_java_class(duk_context *ctx){
    int num = duk_get_top(ctx);
    DEBUG_LOG("ScriptEngine", "duk_new_java_class with args  num %d start", num);
    duk_push_this(ctx);
    duk_get_prop_string(ctx, -1, "className");
    DEBUG_LOG("ScriptEngine", "duk_new_java_class with args %d start", duk_get_top(ctx));
    const char*  className = duk_to_string(ctx, -1);
    DEBUG_LOG("ScriptEngine", "duk_new_java_class with args %d start", duk_get_top(ctx));
    JNIEnv*  env =  get_java_jni_env();
    DEBUG_LOG("ScriptEngine", "duk_new_java_class with args %d start", duk_get_top(ctx));
    jstring  fullClassName = (*env)->NewStringUTF(env, className);
    jobject  instance =  NULL;
    DEBUG_LOG("ScriptEngine", "duk_new_java_class with args %d start", num);
    DEBUG_LOG("ScriptEngine", "duk_new_java_class with args %d start", duk_get_top(ctx));
    if(num == 0){
       	instance = (*env)->CallStaticObjectMethod(env, java_api_class, java_new_instance_method, fullClassName, NULL);
    }else{
    	    jobjectArray args = duk_to_java_object_array(ctx, 0, num, env);
    	    DEBUG_LOG("ScriptEngine", "duk_new_java_class CallStaticObjectMethod start");
    	    instance  = (*env)->CallStaticObjectMethod(env, java_api_class, java_new_instance_method, fullClassName, args);
    	    DEBUG_LOG("ScriptEngine", "duk_new_java_class CallStaticObjectMethod end");
    	    (*env)->DeleteLocalRef(env, args);
    }
    DEBUG_LOG("ScriptEngine", "duk_new_java_class call with %d success", duk_get_top(ctx));
    duk_mark_jsobject_to_java_object(ctx, -2, env, instance);
    (*env)->DeleteLocalRef(env, instance);
    (*env)->DeleteLocalRef(env, fullClassName);
    duk_pop_2(ctx);
    DEBUG_LOG("ScriptEngine", "duk_new_java_class with args %d success", num);
	return 0;
}




void duk_android_fatal_function(duk_context *ctx, duk_errcode_t code, const char *msg){
	LOGE("ScriptEngine","ScriptEngine jni fatal error code %d  msg %s", code, msg);
	abort();
}

static duk_ret_t duk_android_log_print(duk_context *ctx) {
	int n = duk_get_top(ctx);
	switch (n) {
	case 1:
		LOGD("ScriptEngine", "%s", duk_safe_to_string(ctx, 0));
		break;
	case 2:
		LOGD("ScriptEngine", "%s %s", duk_safe_to_string(ctx, 0),
				duk_safe_to_string(ctx, 1));
		break;
	case 3:
		LOGD("ScriptEngine", "%s %s %s", duk_safe_to_string(ctx, 0),
				duk_safe_to_string(ctx, 1), duk_safe_to_string(ctx, 2));
		break;
	case 4: {
		LOGD("ScriptEngine", "%s %s %s %s", duk_safe_to_string(ctx, 0),
				duk_safe_to_string(ctx, 1), duk_safe_to_string(ctx, 2),
				duk_safe_to_string(ctx, 3));
	     }
		break;
	case 0: {
		LOGD("ScriptEngine", "\n");
	}
		break;
	default: {
		LOGW("ScriptEngine",
				"too many args %d to print, javascript print only support less than 4 args\n",
				n);
	}
		break;
	}
	return 0;
}

JNIEXPORT jlong JNICALL Java_com_furture_react_DuktapeEngine_nativeInit(JNIEnv *env, jobject thisObject){
	duk_context *ctx  = duk_create_heap(NULL, NULL, NULL, NULL, &duk_android_fatal_function);
	if(ctx){
		duk_js_ref_setup(ctx);


		duk_push_global_object(ctx);
		duk_push_c_function(ctx, duk_android_log_print, DUK_VARARGS);
	    duk_put_prop_string(ctx, -2, "print");

	    duk_push_c_function(ctx, duk_import_java_class, DUK_VARARGS);
	    duk_put_prop_string(ctx, -2, "importClass");


    	    void* enginePtr = (*env)->NewGlobalRef(env, thisObject);
    	    duk_push_pointer(ctx, enginePtr);
    	    duk_put_prop_string(ctx, -2, JAVA_ENGINE_MARK);


	    duk_get_prototype(ctx, -1);
	    duk_push_c_function(ctx, invoke_java_method_call, DUK_VARARGS);
	    duk_put_prop_string(ctx, -2, JAVA_METHOD_MARK);

	    duk_push_c_function(ctx, duk_java_property_get, DUK_VARARGS);
	    	duk_put_prop_string(ctx, -2, JAVA_GET_MARK);


	    	duk_push_c_function(ctx, duk_java_property_set, DUK_VARARGS);
	    	duk_put_prop_string(ctx, -2, JAVA_SET_MARK);
		duk_pop(ctx);

	    	duk_pop(ctx);
	    	DEBUG_LOG("ScriptEngine", "Native Init Success \n");
		return convert_to_ptr(ctx);
	}
	return -1;
}


JNIEXPORT void JNICALL Java_com_furture_react_DuktapeEngine_nativeRegister
  (JNIEnv *env, jobject thisObject, jlong ptr, jstring key, jobject value){
	duk_context *ctx  = convert_to_context(ptr);
	jboolean iscopy = JNI_FALSE;
	const char* src =  ((*env)->GetStringUTFChars(env, key, &iscopy));
	duk_push_global_object(ctx);
	duk_push_java_object(ctx, env, value);
 	duk_put_prop_string(ctx, -2, src);
	duk_pop(ctx);
	(*env)->ReleaseStringUTFChars(env, key, src);
}


JNIEXPORT jobject JNICALL Java_com_furture_react_DuktapeEngine_nativeExeclute
  (JNIEnv *env, jobject thisObject, jlong  ptr, jstring script){
	jboolean iscopy = JNI_FALSE;
	const char* src = ((*env)->GetStringUTFChars(env, script, &iscopy));
	duk_context *ctx  = convert_to_context(ptr);
	if(duk_peval_string(ctx, src) != DUK_EXEC_SUCCESS){
		 LOGE("ScriptEngine", "ScriptEngine eval_string %s\n", duk_js_error_to_string(ctx, -1));
	     duk_push_null(ctx);
	}
	if(src != NULL){
	    (*env)->ReleaseStringUTFChars(env, script, src);
	}
	return duk_to_java_object(ctx, env, -1);
}

JNIEXPORT jobject JNICALL Java_com_furture_react_DuktapeEngine_nativeCallJs
  (JNIEnv *env, jobject thisObject, jlong ptr, jstring jsTarget, jstring jsMethod, jobjectArray args){
	duk_context *ctx  = convert_to_context(ptr);
	jboolean iscopy = JNI_FALSE;
    const char* targetName = ((*env)->GetStringUTFChars(env, jsTarget, &iscopy));
    DEBUG_LOG("ScriptEngine","Java_com_furture_react_DuktapeEngine_nativeCallJs call on %s", targetName);
	duk_push_global_object(ctx);
    if(duk_get_prop_string(ctx, -1, targetName)){
    	    const char* methodName = ((*env)->GetStringUTFChars(env, jsMethod, &iscopy));
	    duk_push_string(ctx, methodName);
	    jsize length = duk_push_java_object_array(ctx, env, args);
	    DEBUG_LOG("ScriptEngine","Java_com_furture_react_DuktapeEngine_nativeCallJs call  Function %d", length);
	    if(duk_pcall_prop(ctx, -2 - length, length) != DUK_EXEC_SUCCESS){
	     	LOGE("ScriptEngine","ScriptEngine CallJS %s.%s() method %s", targetName, methodName, duk_js_error_to_string(ctx, -1));
	        duk_pop(ctx);
	        duk_push_null(ctx);
	    }
 	    (*env)->ReleaseStringUTFChars(env, jsTarget, targetName);
	    (*env)->ReleaseStringUTFChars(env, jsMethod, methodName);
	    jobject  value =  duk_to_java_object(ctx, env, -1);
	    duk_pop_2(ctx);
	    return value;
    }
    (*env)->ReleaseStringUTFChars(env, jsTarget, targetName);
    duk_pop_2(ctx);
    return NULL;

}

JNIEXPORT jobject JNICALL Java_com_furture_react_DuktapeEngine_nativeCallJSRef
  (JNIEnv *env, jobject thisObject, jlong ptr, jint jsRef, jstring proxyMethod, jobjectArray args){
   duk_context *ctx  = convert_to_context(ptr);
   DEBUG_LOG("ScriptEngine","Java_com_furture_react_DuktapeEngine_nativeCallJSRef start %d", duk_get_top(ctx));
   duk_push_js_ref(ctx, jsRef);
   if(duk_is_function(ctx, -1)){
	      DEBUG_LOG("ScriptEngine","Java_com_furture_react_DuktapeEngine_nativeCallJSRef is Function %d", jsRef);
	   	  jsize length = duk_push_java_object_array(ctx, env, args);
	   	   DEBUG_LOG("ScriptEngine","Java_com_furture_react_DuktapeEngine_nativeCallJSRef call  Function %d", length);
		  if(duk_pcall(ctx, length) != DUK_EXEC_SUCCESS){
			  jboolean iscopy = JNI_FALSE;
			  const char* method = ((*env)->GetStringUTFChars(env, proxyMethod, &iscopy));
			  LOGE("ScriptEngine","ScriptEngine CallJSRef   %s method exception %s", method, duk_js_error_to_string(ctx, -1));
			  duk_pop(ctx);
			  duk_push_null(ctx);
			  if(method != NULL){
			     (*env)->ReleaseStringUTFChars(env, proxyMethod, method);
			  }
		  }
		  DEBUG_LOG("ScriptEngine","Java_com_furture_react_DuktapeEngine_nativeCallJSRef call  Function %d", length);
		  jobject  value =  duk_to_java_object(ctx, env, -1);
		  duk_pop(ctx);
		  return value;
   }
   jboolean iscopy = JNI_FALSE;
   const char* method = ((*env)->GetStringUTFChars(env, proxyMethod, &iscopy));
   duk_push_string(ctx, method);
   jsize length = duk_push_java_object_array(ctx, env, args);
   DEBUG_LOG("ScriptEngine","Java_com_furture_react_DuktapeEngine_nativeCallJSRef call Object  Function %d", length);
   if(duk_pcall_prop(ctx, -2 - length, length) != DUK_EXEC_SUCCESS){
	   LOGE("ScriptEngine","ScriptEngine CallJSRef  %d proxy method %s exception %s", jsRef, method, duk_js_error_to_string(ctx, -1));
	   duk_pop(ctx);
	   duk_push_null(ctx);
   }
   (*env)->ReleaseStringUTFChars(env, proxyMethod, method);
   DEBUG_LOG("ScriptEngine","Java_com_furture_react_DuktapeEngine_nativeCallJSRef call Object success %d", duk_get_type(ctx, -1));
   jobject  value =  duk_to_java_object(ctx, env, -1);
   duk_pop_2(ctx);
   return value;
}


JNIEXPORT void JNICALL Java_com_furture_react_DuktapeEngine_nativeFinalizeJSRef
  (JNIEnv *env, jobject thisObject, jlong ptr, jint ref){
	 duk_context *ctx  = convert_to_context(ptr);
	 duk_push_js_ref(ctx, ref);
	 if(duk_get_prop_string(ctx, -1, JS_REF_MARK)){
	     jweak  weakRef = duk_to_pointer(ctx, -1);
	     (*env)->DeleteWeakGlobalRef(env, weakRef);
	 }
	 duk_pop_2(ctx);
	 duk_js_unref(ctx, ref);
}




JNIEXPORT void JNICALL Java_com_furture_react_DuktapeEngine_nativeDestory
  (JNIEnv * env, jobject thisObject, jlong ptr){
	duk_context *ctx  = convert_to_context(ptr);
	if(ctx){
        jobject enginePtr  = get_engine_from_context(ctx);
        int length = duk_js_ref_size(ctx);
		for(int i=1; i <= length; i++){
			duk_push_js_ref(ctx, i);
			if(duk_is_object(ctx, -1)){
				if(duk_get_prop_string(ctx, -1, JS_REF_MARK)){
					  jweak  weakRef = duk_to_pointer(ctx, -1);
					  if(weakRef != NULL){
					      (*env)->DeleteWeakGlobalRef(env, weakRef);
					  }
					  DEBUG_LOG("ScriptEngine", "Free jweak Ref onJSRef %d", i);
			     }
				 duk_pop(ctx);
			}
			duk_pop(ctx);
		}
		duk_destroy_heap(ctx);
		if(enginePtr != NULL){
		    (*env)->DeleteGlobalRef(env, enginePtr);
		}
	}
}

static jclass findGlobalRefClass(JNIEnv* env, const char* className){
	 jclass cls = (*env)->FindClass(env, className);
	 jclass global_ref_class = (*env)->NewGlobalRef(env, cls);
	(*env)->DeleteLocalRef(env, cls);
	return global_ref_class;
}


JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void* reserved) {
	JNIEnv* env = NULL;
	if ((*vm)->GetEnv(vm, (void**) &env, JNI_VERSION_1_6) != JNI_OK) {
		return -1;
	}
	jvm  = vm;
	if (java_api_class == NULL) {
		jclass cls = (*env)->FindClass(env, "com/furture/react/JavaUtils");
		java_api_class = (*env)->NewGlobalRef(env, cls);
		(*env)->DeleteLocalRef(env, cls);
	}

	if (java_function_method == NULL) {
		java_function_method =
				(*env)->GetStaticMethodID(env, java_api_class, "invoke",
						"(Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;");
	}

	if (java_field_get_method == NULL) {
		java_field_get_method = (*env)->GetStaticMethodID(env, java_api_class,
				"get", "(Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;");
	}

	if (java_import_class_method == NULL) {
		java_import_class_method = (*env)->GetStaticMethodID(env,
				java_api_class, "importClass", "(Ljava/lang/String;)Ljava/lang/Class;");
	}

	if (java_field_set_method == NULL) {
		java_field_set_method = (*env)->GetStaticMethodID(env, java_api_class,
				"set", "(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)V");
	}

	if (java_new_instance_method == NULL) {
		java_new_instance_method = (*env)->GetStaticMethodID(env,
				java_api_class, "newInstance", "(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;");
	}

	if (java_exception_get_stack_trace_method == NULL) {
		java_exception_get_stack_trace_method = (*env)->GetStaticMethodID(env, java_api_class, "getStackTrace",
				"(Ljava/lang/Throwable;)Ljava/lang/String;");
	}

	if (js_ref_class == NULL) {
		jclass cls = (*env)->FindClass(env, "com/furture/react/JSRef");
		js_ref_class = (*env)->NewGlobalRef(env, cls);
		(*env)->DeleteLocalRef(env, cls);
	}

	if (js_ref_new_method == NULL) {
		js_ref_new_method = (*env)->GetMethodID(env, js_ref_class, "<init>", "(Lcom/furture/react/DuktapeEngine;I)V");
	}

	if (js_ref_get_ref_method == NULL) {
		js_ref_get_ref_method = (*env)->GetMethodID(env, js_ref_class, "getRef", "()I");
	}

	if(java_boolean_class == NULL){
		java_boolean_class= findGlobalRefClass(env, "java/lang/Boolean");
	}

	if(java_integer_class  == NULL){
		java_integer_class = findGlobalRefClass(env, "java/lang/Integer");
	}
	if(java_long_class  == NULL){
		java_long_class = findGlobalRefClass(env, "java/lang/Long");
	}

	if(java_double_class  == NULL){
		java_double_class = findGlobalRefClass(env, "java/lang/Double");
	}

	if(java_float_class  == NULL){
		java_float_class = findGlobalRefClass(env, "java/lang/Float");
	}

	if(java_short_class  == NULL){
		java_short_class = findGlobalRefClass(env, "java/lang/Short");
	}

	if(java_byte_class == NULL){
		java_byte_class = findGlobalRefClass(env, "java/lang/Byte");
	}

	if(java_number_class == NULL){
		java_number_class = findGlobalRefClass(env, "java/lang/Number");
	}

	if(java_number_get_double_value_method  == NULL){
		java_number_get_double_value_method = (*env)->GetMethodID(env, java_number_class, "doubleValue", "()D");
	}

	if(java_boolean_get_boolean_value_method == NULL){
		java_boolean_get_boolean_value_method = (*env)->GetMethodID(env, java_boolean_class, "booleanValue", "()Z");
	}



	DEBUG_LOG("ScriptEngine","JNI_OnLoad Success");
	return JNI_VERSION_1_6;
}

JNIEnv*  get_java_jni_env()
{
    JavaVMAttachArgs args = {JNI_VERSION_1_6, 0, 0};
    JNIEnv* env;
    (*jvm)->AttachCurrentThread(jvm, &env, &args);
    return env;
}

JNIEXPORT void JNICALL JNI_OnUnload(JavaVM* vm, void* reserved) {
	JNIEnv* env = NULL;
	if ((*vm)->GetEnv(vm, (void**) &env, JNI_VERSION_1_6) != JNI_OK) {
		return;
	}
	if (java_api_class != NULL) {
		 (*env)->DeleteGlobalRef(env, java_api_class);
		 java_api_class = NULL;
	}

	if (js_ref_class != NULL) {
		  (*env)->DeleteGlobalRef(env, java_api_class);
			js_ref_class = NULL;
	}

	if (java_boolean_class != NULL) {
		 (*env)->DeleteGlobalRef(env, java_api_class);
		 java_boolean_class = NULL;
	}

	if (java_integer_class != NULL) {
		 (*env)->DeleteGlobalRef(env, java_integer_class);
		 java_integer_class = NULL;
	}
	if (java_long_class != NULL) {
		 (*env)->DeleteGlobalRef(env, java_long_class);
		 java_long_class = NULL;
	}

	if (java_double_class != NULL) {
		 (*env)->DeleteGlobalRef(env, java_double_class);
		 java_double_class = NULL;
	}

	if (java_float_class != NULL) {
		 (*env)->DeleteGlobalRef(env, java_float_class);
		 java_float_class = NULL;
	}

	if (java_short_class != NULL) {
		 (*env)->DeleteGlobalRef(env, java_short_class);
		 java_short_class = NULL;
	}

	if (java_byte_class != NULL) {
		(*env)->DeleteGlobalRef(env, java_byte_class);
		java_byte_class  = NULL;
	}

	if (java_number_class != NULL) {
		(*env)->DeleteGlobalRef(env, java_number_class);
		java_number_class = NULL;
	}
	jvm = NULL;
	DEBUG_LOG("ScriptEngine","JNI_OnUnload Success");
}
