/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>
#include "config.h"
#include "refs.h"

/* Header for class com_furture_react_DuktapeEngine */

#ifndef _Included_com_furture_react_DuktapeEngine
#define _Included_com_furture_react_DuktapeEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_furture_react_DuktapeEngine
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_furture_react_DuktapeEngine_nativeInit
  (JNIEnv *, jobject);


/*
 * Class:     com_furture_react_DuktapeEngine
 * Method:    nativeRegister
 * Signature: (JLjava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_furture_react_DuktapeEngine_nativeRegister
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     com_furture_react_DuktapeEngine
 * Method:    nativeExeclute
 * Signature: (JLjava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_furture_react_DuktapeEngine_nativeExeclute
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_furture_react_DuktapeEngine
 * Method:    nativeCallJs
 * Signature: (JLjava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_furture_react_DuktapeEngine_nativeCallJs
  (JNIEnv *, jobject, jlong, jstring, jstring, jobjectArray);

/*
 * Class:     com_furture_react_DuktapeEngine
 * Method:    nativeCallJSRef
 * Signature: (JILjava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_furture_react_DuktapeEngine_nativeCallJSRef
  (JNIEnv *, jobject, jlong, jint, jstring, jobjectArray);

/*
 * Class:     com_furture_react_DuktapeEngine
 * Method:    nativeFinalizeJSRef
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_furture_react_DuktapeEngine_nativeFinalizeJSRef
  (JNIEnv *, jobject, jlong, jint);



/*
 * Class:     com_furture_react_DuktapeEngine
 * Method:    nativeDestory
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT void JNICALL Java_com_furture_react_DuktapeEngine_nativeDestory
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
